#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[[DRY_RUN]] $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"

  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "---------------- dev-env ----------------"

update_files() {
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log "    removing: rm -rf $directory"

            if [[ $dry_run == "0" ]]; then
                rm -rf $directory
            fi

            log "    copying env: cp $c $2"
            if [[ $dry_run == "0" ]]; then
                cp -r ./$c $2
            fi
        done

    )
    popd &> /dev/null
}

copy_file() {
  from=$1
  to=$2

  name=$(basename $from)

  if [ -n "$filter" ] && echo "$name" | grep -qv $filter; then
    log "filtering $name"
    return
  fi

  execute rm $to/$name
  execute cp $from $to/$name

}

update_files .config $HOME/.config
update_files .local $HOME/.local
copy_file .wezterm.lua $HOME
copy_file .tmux.conf $HOME
copy_file .gitconfig $HOME
copy_file ./.local/scripts/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
copy_file ./dev-env $HOME/.local/scripts/dev-env

hyprctl reload

