#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[[DRY_RUN]] $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"

  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "---------------- dev-env ----------------"

copy_dir() {
  from=$1
  to=$2


  pushd $from > /dev/null
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)

  for dir in $dirs; do
    if [ -n "$filter" ] && echo "$dir" | grep -qv $filter; then
      log "filtering $dir"
      continue
    fi

    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd > /dev/null
}

copy_file() {
  from=$1
  to=$2

  name=$(basename $from)

  if [ -n "$filter" ] && echo "$name" | grep -qv $filter; then
    log "filtering $name"
    return
  fi

  execute rm $to/$name
  execute cp $from $to/$name

}

copy_dir .config $HOME/.config
copy_dir .local $HOME/.local
copy_file .wezterm.lua $HOME
copy_file .tmux.conf $HOME
copy_file .gitconfig $HOME
copy_file ./.local/scripts/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
copy_file ./dev-env $HOME/.local/scripts/dev-env

hyprctl reload

