require("mf.options")
require("mf.keymaps")
require("mf.plugins")
require("mf.colorscheme")
require("mf.cmp")
require("mf.lsp")
require("mf.telescope")
require("mf.treesitter")
require("mf.autopairs")
require("mf.comment")
require("mf.gitsigns")
require("mf.nvim-tree")
require("mf.bufferline")
require("mf.toggleterm")
require("mf.lualine")
require("mf.copilot")

require("colorizer").setup()
